import time
import allure
from conftest import web_browser
from locators.locators_hunter import Hunter


@allure.title('тесты мейна')
def test_hunter(web_browser):
    page = Hunter(web_browser)
    time.sleep(2)
#проверка скипа
    # page.btn_character.click()
    # page.btn_character_hunter.click()
    # time.sleep(2)
    # page.btn_next.click()
    # page.btn_next.click()
    # page.btn_next.click()
    # page.btn_next.click()
    # page.btn_next.click()
    # page.btn_next.click()
    # time.sleep(2)
    # page.btn_prev.click()
    # page.btn_prev.click()
    # page.btn_prev.click()
    # page.btn_prev.click()
    # page.btn_prev.click()
    # page.btn_prev.click()
    # time.sleep(2)

#проверка персонажа
    page.btn_character.click()
    page.btn_character_hunter.click()
    time.sleep(2)
    page.btn_next.click()
    page.btn_next.click()
    page.btn_next.click()
    page.btn_next.click()
    page.btn_next.click()
    time.sleep(2)
    page.btn_nightwatch.click()
    time.sleep(10)
    page.btn_nextturn.click()
    page.btn_nextturn.click()
    page.btn_nextturn.click()
    page.btn_nextturn.click()
    time.sleep(2)
    page.btn_prevturn.click()
    page.btn_prevturn.click()
    page.btn_prevturn.click()
    page.btn_prevturn.click()
    time.sleep(2)

    page.btn_foolsgold.click()
    time.sleep(10)
    page.btn_nextturn.click()
    page.btn_nextturn.click()
    page.btn_nextturn.click()
    page.btn_nextturn.click()
    time.sleep(2)
    page.btn_prevturn.click()
    page.btn_prevturn.click()
    page.btn_prevturn.click()
    page.btn_prevturn.click()
    time.sleep(2)
